backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

# (опционально) включить редакторский workflow с черновиками/ревью
# publish_mode: editorial_workflow

collections:
  - name: "posts_en"
    label: "Posts (EN)"
    folder: "content/en/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Featured image", name: "featuredImage", widget: "image", required: false }
      - { label: "Featured image alt", name: "featuredImageAlt", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts_uk"
    label: "Пости (UK)"
    folder: "content/uk/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Чернетка", name: "draft", widget: "boolean", default: false }
      - { label: "Теги", name: "tags", widget: "list", required: false }
      - { label: "Категорії", name: "categories", widget: "list", required: false }
      - { label: "Короткий опис", name: "excerpt", widget: "string", required: false }
      - { label: "Обкладинка", name: "featuredImage", widget: "image", required: false }
      - { label: "Alt для обкладинки", name: "featuredImageAlt", widget: "string", required: false }
      - { label: "Текст", name: "body", widget: "markdown" }

